feat: first implementation 🌓
restqa/plugin pull request #2
Opened 2021-09-05 12:55 UTC by tony-go

Hi 👋 

Following our discussion in the issue #1 

I'll implement the first version of the plugin factory 🎉 

My work will follow these steps:

- [x] Scaffold project
- [x] Add init / constructor options
- [ ] Add step definition feature (no hooks, no word atm)
- [ ] Add documentation
- [ ] Publish 🎉

2021-09-14 03:41 UTC, olivierodo requested changes
A few changes that needs tp be considered

2021-09-14 03:41 UTC, olivierodo commented on .github/build.yml
> +on: [push]
In order to trigger the github action also when we are receiving a PR we should add the event `pull_request`

2021-09-14 03:41 UTC, olivierodo commented on package.json
> +    "@cucumber/cucumber": "^7.3.1"
I don't think we need `@cucumber/cucumber` into the dependencies.
I believe its  only used by `index.d.ts`, could we move it to the devDependencies

2021-09-14 03:41 UTC, olivierodo commented on test/user.test.js
> +      expect(pf._state).toEqual({[property]: value});
I can't see the property `_state` into the index.d.ts...
Should we consider to create a getter ? `getState()` ?

2021-09-14 03:48 UTC, olivierodo commented
Regarding the test i think there is one missing pieces, we should consider to create a high level test (chicago style 🤓).
Something like
```js
const config = {}
const cucumberInstance = {}
const pf = new PluginFactory({name: "plugin"});
pf
  .addGivenStep(...)
  .addBeforeHook(...)
  ._apply(cucumberInstance, config)
 
expect(cucumberinstance.Given).toHaveBeenCalled()
expect(pf.getConfig()).tpEqual(config)
...
```

2021-09-14 07:34 UTC, tony-go commented on test/user.test.js
> +      expect(pf._state).toEqual({[property]: value});
There are three levels of properties/methods there
- Public: without `_` prefix and mentioned in `index.d.ts`
- Private used by core (bootstrap): with a `_` prefix and mentioned in `index.d.ts`
- Private:  with a `_` prefix and *not* mentioned in `index.d.ts`

I sometimes use them (the last one) in my test. Let me know if you think it's a bad practice.

2021-09-14 07:35 UTC, tony-go commented on test/user.test.js
> +      expect(pf._state).toEqual({[property]: value});
(I forgot to add `_getState` so)

2021-09-14 07:36 UTC, tony-go commented
> Regarding the test i think there is one missing pieces, we should consider to create a more high level test (chicago style 🤓).
> Something like
> 
> ```js
> const config = {}
> const cucumberInstance = {}
> const pf = new PluginFactory({name: "plugin"});
> pf
>   .addGivenStep(...)
>   .addBeforeHook(...)
>   ._apply(cucumberInstance, config)
>  
> expect(cucumberinstance.Given).toHaveBeenCalled()
> expect(pf.getConfig()).tpEqual(config)
> ...
> ```

So you mean a test that mimics the final usage?

2021-09-14 17:12 UTC, olivierodo commented on package.json
> +  "name": "@restqa/plugin",
-> `@restqa/plugins`

2021-09-14 23:05 UTC, olivierodo commented
> So you mean a test that mimics the final usage? 

Correct

2021-09-15 04:31 UTC, olivierodo commented on README.md
> +      (expectedUserAge) => this.state.user.age === expectedUserAge
The way to access to state should be `this['plugin-name'].user.age === expectedUserAge`

basically in order to avoid collision between plugins, the state of current plugin will be accessible through it plugin name

2021-09-15 05:41 UTC, tony-go commented
> > So you mean a test that mimics the final usage?
> 
> Correct

So could you check the `functional.test.js` file and tell me WDYT ? @olivierodo

2021-09-15 06:46 UTC, olivierodo approved these changes

2021-09-16 05:49 UTC, olivierodo commented
LGTM 🤓

2021-09-16 06:41 UTC, merged